///
/// Interpreter - Responsible for interpreting the Abstract Syntax Tree made within the Parser. In essence, it performs
///     the calculations and operations that the user has written in the code, using the visitor pattern from the Node
///     Visitor interface to traverse the tree and perform the operations. Errors are a part of calculations, so they
///     are thrown as when they occur (e.g. incorrect types, division by zero, etc.).
///

package Interpreter;

import AbstractSyntaxTree.Statements.*;
import Interpreter.Value.DataType;
import AbstractSyntaxTree.NodeVisitor;
import AbstractSyntaxTree.Node;
import AbstractSyntaxTree.Expressions.*;
import AbstractSyntaxTree.Statements.For;
import AbstractSyntaxTree.Statements.While;
import Language.BuiltInFunctions;
import Lexer.OperationCode;
import Lexer.Token;
import Language.Error;
import Language.Error.ErrorType;

import ch.obermuhlner.math.big.BigDecimalMath;
import java.math.BigDecimal;
import java.math.BigInteger;
import java.util.ArrayList;
import java.util.List;
import java.util.function.BiFunction;
import java.util.function.BiPredicate;
import java.util.function.IntPredicate;


public class Interpreter implements NodeVisitor {

    /* PUBLIC */

    /** Constructors **/

    /**/
    /*
    Interpreter.Interpreter()

    NAME

        Interpreter - constructor for the interpreter.

    SYNOPSIS

        Interpreter(SymbolTable a_globalScope);
            a_globalScope    -> the global scope of the program.

    DESCRIPTION

        Initializes the current scope of the interpreter to the global scope, so
        if when we define a function, or declare a variable, we have somewhere
        to put it.

    RETURNS

        Nothing - it's a constructor.

    */
    /**/
    public Interpreter(SymbolTable a_globalScope) {
        m_currentScope = a_globalScope;
    }
    /* Interpreter(SymbolTable a_globalScope); */


    /** Methods **/

    /**/
    /*
    Interpreter.Interpret()

    NAME

        Interpret - interprets the Abstract Syntax Tree (AST) generated by the
        parser, evaluating the nodes it comes across.

    SYNOPSIS

        public Value Interpret(List<Node> a_tree);
            a_tree    -> the list of nodes/statements that make up the AST.

    DESCRIPTION

        Interprets the AST by traversing the tree and interpreting the nodes it
        in order of the list. It will evaluate the nodes and return the result
        of the last evaluated node. This function is the driver for the actual
        evaluation of the code.

        At any point in the traversal when we have a runtime error (e.g.
        incorrect types arithmetic, or division by zero), it will be thrown as
        an error immediately at the node it occurs. Done to inform the user.
        Break and continue exceptions are caught and reported as runtime errors
        here if not caught within parser - it is not a syntax error as they were
        defined in a loop, but not in the correct context at runtime.

    RETURNS

        The result of the last evaluated node. If it is a statement, like a
        while loop, it will return our version of NULL as everything must return
        a value in our language.

    */
    /**/
    public Value Interpret(List<Node> a_tree) {
        Value result = Value.NULL;

        // Traverse the tree and interpret the nodes
        for (Node node : a_tree) {
            try { result = node.Accept(this); }

            // Very specific problem when a function gets defined in a loop and then outside of it. Is a runtime error
            //      as it's syntactically is correct, but function cannot jump out of a loop that isn't being executed.
            catch (Jump.BreakException error) { ErrorOnJump("Break", error.GetLineNumber());}
            catch (Jump.ContinueException error) { ErrorOnJump("Continue", error.GetLineNumber());}
        }

        // Return the last evaluated result
        return result;
    }
    /* public Value Interpret(List<Node> a_tree); */


    /*
     *      Visiting Statements - Changing state and performing actions
     */

    /**/
    /*
    Interpreter.VisitFunction()

    NAME

        VisitFunction - binds a function definition to the current scope.

    SYNOPSIS

        public Value VisitFunction(Function a_function);
            a_function    -> the function node to visit.

    DESCRIPTION

        Binds the function to the current scope of evaluation, so it can be
        called later on in. Responsible for user defined functions, not
        built-ins. Simply put, we add the function name and the corresponding
        function to the current scope.

        For example, 'DEF add(x, y); x + y END' would bind the function 'add'
        to the symbol table, storing the parameters and body of the function.

    RETURNS

        Our NULL Value - everything must evaluate to something in our language,
        but as a statement, we don't random information.

    */
    /**/
    @Override
    public Value VisitFunction(Function a_function) {
        // Add the function to the global scope
        m_currentScope.PutIdentifier(a_function.GetFunctionName(), new Value(a_function));

        // Don't want any value returned from a function definition - done to avoid output in CLI
        return Value.NULL;
    }
    /* public Value VisitFunction(Function a_function); */

    /**/
    /*
    Interpreter.VisitIfElseifElse()

    NAME

        VisitIfElseifElse - visits an if-elseif-else conditional statement,
        executing the first body that evaluates to true.

    SYNOPSIS

        public Value VisitIfElseifElse(IfElseifElse a_conditional);
            a_conditional    -> the if-elseif-else conditional statement to
                visit.

    DESCRIPTION

        Evaluates the if-elseif-else conditional chain by checking each
        condition in order. As soon as one condition evaluates to true (which we
        find by visiting the expression), the body of that condition is executed
        and the result is returned. This expression must be a BOOLEAN Value, if
        it isn't, a type error is thrown.

        Lastly, if no conditions are met, and there is an else body, it is
        executed. If no else, then no statement will be executed.

        For example, 'IF x < 5 THEN 1 END' would return the Value of 1.

    RETURNS

        The last resulted Value from the executed body of the condition that
        was met, or the else body if no conditions were met. If no else body,
        then NULL Value gets returned - everything must evaluate to something.

    */
    /**/
    @Override
    public Value VisitIfElseifElse(IfElseifElse a_conditional) {
        // Loop through all the conditions until we hit a true (if one). If size of list is one it is just if, otherwise
        //      it is an elseif chain. Doesn't matter regardless as the first true will be executed.
        for (ConditionalField field : a_conditional.GetConditions()) {
            // Make sure the condition is a boolean, if not, type error
            Value condition = field.GetCondition().Accept(this);
            EnforceGenericType(DataType.BOOLEAN, condition, field.GetLineNumber());

            // If the condition is true, execute the body and return the result
            if (condition.AsBoolean()) { return field.GetBody().Accept(this); }
        }

        // No conditions were met, if there is an else body, execute it
        if (a_conditional.HasElse()) { return a_conditional.GetElseBody().Accept(this); }

        // No conditions were met and no else body, return our NULL value
        return Value.NULL;
    }
    /* public Value VisitIfElseifElse(IfElseifElse a_conditional); */


    /**/
    /*
    Interpreter.VisitWhile()

    NAME

        VisitWhile - visits and evaluates a while loop.

    SYNOPSIS

        public Value VisitWhile(While a_while);
            a_while    -> the while loop to visit and evaluate.

    DESCRIPTION

        Evaluates the condition of the while loop, and if it is true, executes
        the body of the loop. This process is repeated until the condition is no
        longer true. If a break is encountered (through a Jump BreakException),
        the loop is stopped, and if a continue statement is encountered
        (through a Jump ContinueException), the current iteration gets skipped.
        The condition must always be a BOOLEAN Value, if it isn't, a type error
        gets thrown.

        For example, 'WHILE x < 5 THEN PRINT(x); x = x + 1 END' would print:
        '01234'.

    RETURNS

        Our NULL Value - everything must evaluate to something in our language,
        but as a statement it doesn't have any meaningful information to return.

    */
    /**/
    @Override
    public Value VisitWhile(While a_while) {
        // Evaluate the condition and ensure it is a boolean
        Value condition = a_while.GetCondition().Accept(this);
        EnforceGenericType(DataType.BOOLEAN, condition, a_while.GetLineNumber());

        while (condition.AsBoolean()) {
            // Execute the body of the while loop
            try { a_while.GetBody().Accept(this); }
            // If a break is encountered, stop the loop
            catch (Jump.BreakException e) { break;}
            // Just want to stop current iteration (will evaluate condition again after)
            catch (Jump.ContinueException ignored) { }

            // Update the condition for the next iteration, ensure it is still a boolean
            condition = a_while.GetCondition().Accept(this);
            EnforceGenericType(DataType.BOOLEAN, condition, a_while.GetLineNumber());
        }

        // Don't want any value returned from a while loop - done to avoid output in CLI
        return Value.NULL;
    }
    /* public Value VisitWhile(While a_while); */

    /**/
    /*
    Interpreter.VisitFor()

    NAME

        VisitFor - visits and evaluates a for loop.

    SYNOPSIS

        public Value VisitFor(For a_for);
            a_for    -> the for loop to visit and evaluate.

    DESCRIPTION

        Evaluates the assignment, end value and increment of the for loop. These
        Values must all be of type INTEGER, and if they aren't a type error is
        thrown. The loop will then iterate from the assignment to the end value
        (inclusive) by the increment. Steps/Increments can be negative, but it
        can result in an infinite loop. In order to facilitate this, we
        calculate the distance between the start and end values and iterate that
        many times.

        Similar to the while loop, if a break is encountered (through a Jump
        BreakException), the loop is stopped, and if a continue statement is
        encountered (through a Jump ContinueException), the current iteration
        gets skipped.

        For example, 'FOR i = 1 TO 5 THEN PRINT(i) END' would print '12345'. And
        'FOR i = 5 TO 1 STEP -1 THEN PRINT(i) END' would print '54321'.

    RETURNS

        Our NULL Value - everything must evaluate to something in our language,
        but as a statement it doesn't have any meaningful information to return.

    */
    /**/
    @Override
    public Value VisitFor(For a_for) {
        // Get the assignment, end value and increment for the for loop
        Value assignment = a_for.GetAssignment().Accept(this);
        Value endValue = a_for.GetEndValue().Accept(this);
        Value increment = a_for.GetIncrement().Accept(this);

        // Ensure they are all integers. Could allow floats, but I find it is more confusing. For loops are generally
        //      used to iterate a certain whole number of times, and it muddies the water to say 1.5 to 5.5.
        EnforceForLoopTypes(assignment, endValue, increment, a_for.GetLineNumber());

        // Convert all to integers here - easier to work with than calling AsInteger() every time
        String variableName = a_for.GetAssignment().GetVariableName();
        BigInteger index = assignment.AsInteger();
        BigInteger step = increment.AsInteger();
        // The loopIterations is just the distance between the start and end values, regardless of direction
        BigInteger loopIterations = index.subtract(endValue.AsInteger()).abs();

        // Loop until the index is above distance inclusive (will be infinite if step is opposite direction or 0)
        // Help received: https://stackoverflow.com/a/34677687
        while (index.compareTo(loopIterations) <= 0) {
            // Update to the actual value, will change if overridden in block - similar to fortran
            m_currentScope.PutIdentifier(variableName, new Value(index));

            try { a_for.GetBody().Accept(this); }
            // If a break is encountered, stop the loop
            catch (Jump.BreakException e) { break; }
            // Just want to stop current iteration
            catch (Jump.ContinueException ignored) { }

            // Increment the index by the step
            index = index.add(step);
        }

        // Don't want any value returned from a for loop - done to avoid output in CLI
        return Value.NULL;
    }
    /* public Value VisitFor(For a_for); */

    /**/
    /*
    Interpreter.VisitBody()

    NAME

        VisitBody - visits and evaluates a block of statements.

    SYNOPSIS

        public Value VisitBody(Body a_body);
            a_body    -> the block of statements to visit and evaluate.

    DESCRIPTION

        Evaluates each statement in the block of statements by traversing down
        each statement found within our List of nodes. The result of the Last
        Value is returned

        For example, 'IF TRUE THEN PRINT("HELLO"); PRINT("!") END', where the
        body is the two print statements, would print 'HELLO!'.

    RETURNS

        The result of the last evaluated statement in the body. Helpful for
        conditional statements in the CLI.

    */
    /**/
    @Override
    public Value VisitBody(Body a_body) {
        Value result = Value.NULL;

        // Traverse down each statement in the block
        for (Node statement : a_body.GetStatements()) {
            result = statement.Accept(this);
        }

        // Return the result of the last statement (helpful for conditional statements in CLI)
        return result;
    }
    /* public Value VisitBody(Body a_body); */

    /**/
    /*
    Interpreter.VisitJump()

    NAME

        VisitJump - visits a jump statement (break, continue, return), throwing
        their respective exceptions.

    SYNOPSIS

        public Value VisitJump(Jump a_jump);
            a_jump    -> the jump statement to visit.

    DESCRIPTION

        Throws a Jump Exception based on the type of jump statement. If it is a
        break, it will throw a BreakException, if continued, a ContinueException,
        and if it is a return, it will throw a ReturnException with the Value of
        the expression. We throw exceptions as control flow as we are likely
        deeply nested in the tree, and it is easier to catch and handle them
        then try to return a value up the tree and check the condition there.

        For example, 'WHILE TRUE THEN BREAK; PRINT("HI") END' would stop the
        loop before getting to the print statement.

    RETURNS

        Nothing - it throws an exception, so it doesn't return anything. If a
        jump statement is not one of the three, an IllegalStateException is
        thrown because we should never be here without a valid jump type.

    */
    /**/
    @Override
    public Value VisitJump(Jump a_jump) {
        // Help received: IDE suggestion for switch expression
        switch (a_jump.GetJumpType()) {
            case BREAK -> throw new Jump.BreakException(a_jump.GetLineNumber());
            case CONTINUE -> throw new Jump.ContinueException(a_jump.GetLineNumber());
            // Jump back to the caller with the value
            case RETURN -> throw new Jump.ReturnException(a_jump.GetExpression().Accept(this));

            // Should never be able to happen, report a real error
            default -> throw new IllegalStateException("Invalid jump type: " + a_jump.GetJumpType().LABEL);
        }
    }
    /* public Value VisitJump(Jump a_jump); */



    /*
     *      Visiting Expressions - Performing operations and getting a value
     */

    /**/
    /*
    Interpreter.VisitAssignment()

    NAME

        VisitAssignment - visits and evaluates an assignment statement.

    SYNOPSIS

        public Value VisitAssignment(Assignment a_assignment);
            a_assignment    -> the assignment statement to visit and bind to the
                current scope.

    DESCRIPTION

        Evaluates the expression of the assignment statement and binds the
        result to the current scope we are in. The value of the expression is
        returned, as some languages do not return anything on assignment, but we
        do. If the variable is already in the scope, it will be overridden.

        For example, 'LET x = 5 + 1' would first evaluate '5 + 1' and then bind
        the result to 'x', so 'x' would be bound to '6'.

    RETURNS

        The value of the expression that was assigned to the variable.

    */
    /**/
    @Override
    public Value VisitAssignment(Assignment a_assignment) {
        // Get the value of the expression
        Value value = a_assignment.GetExpression().Accept(this);

        // Assign the value to the variable
        m_currentScope.PutIdentifier(a_assignment.GetVariableName(), value);

        // Some languages don't return anything on assignment, but we are different, return the value
        return value;
    }
    /* public Value VisitAssignment(Assignment a_assignment); */

    /**/
    /*
    Interpreter.VisitBinaryOperator()

    NAME

        VisitBinaryOperator - visits and evaluates a binary operation.

    SYNOPSIS

        public Value VisitBinaryOperator(BinaryOperator a_binary);
            a_binary    -> the binary operation to visit and evaluate.

    DESCRIPTION

        Evaluates the left and right expressions of the binary operation and
        performs the operation. The result of the operation is returned. If the
        operation is not valid (e.g. adding a string and a number), a type error
        is thrown. If the operation is division or modulo, and the right value
        is 0, a division by zero error is thrown.

        Done by traversing down the left expression, then the right, and then
        passing the value off to the helper function to actually perform the
        operation.

        For example, '1 + 2' would return the Value of 3, and '5 / 0' would
        throw a division by zero error.

    RETURNS

        The result of the binary operation.

    */
    /**/
    @Override
    public Value VisitBinaryOperator(BinaryOperator a_binary) {
        // Traverse down left to the value, then right (post-order traversal)
        Value leftValue = a_binary.GetLeftExpression().Accept(this);
        Value rightValue = a_binary.GetRightExpression().Accept(this);

        // Perform the binary operation (1 + 1, 2 * 3, etc.)
        return EvaluateBinaryOperator(leftValue, a_binary.GetToken(), rightValue);
    }
    /* public Value VisitBinaryOperator(BinaryOperator a_binary); */

    /**/
    /*
    Interpreter.VisitIndex()

    NAME

        VisitIndex - visits and evaluates an index operation.

    SYNOPSIS

        public Value VisitIndex(Index a_index);
            a_index    -> the index operation to visit and evaluate.

    DESCRIPTION

        Evaluates the accessee and index of the index operation. If the index is
        ranged, it evaluates the start and end indices. The result of the
        operation is returned. If the index is out of bounds, an index out of
        bounds error is thrown.

        For example, 'list:1' would return the Value at index 1 in the list, and
        'list:1|3]' would return a list Value for the indices at 1 and 2 in
        the list (not inclusive).

    RETURNS

        The result of the index operation. So the element at a specific index or
        a list of elements between two indices.

    */
    /**/
    @Override
    public Value VisitIndex(Index a_index) {
        // Traverse down the accessee expression and the index expression
        Value accesseeValue = a_index.GetAccessee().Accept(this);

        // If ranged deal with starting and ending indices
        if (a_index.IsRanged()) {
            Value startIndex = a_index.GetStartIndex().Accept(this);
            Value endIndex = a_index.GetEndIndex().Accept(this);
            return AccessRangedSubscript(accesseeValue, startIndex, endIndex, a_index.GetToken().GetLineNumber());
        }

        Value index = a_index.GetIndex().Accept(this);
        return AccessIndexSubscript(accesseeValue, index, a_index.GetToken().GetLineNumber());
    }
    /* public Value VisitIndex(Index a_index); */

    /**/
    /*
    Interpreter.VisitUnaryOperator()

    NAME

        VisitUnaryOperator - visits and evaluates a unary operation.

    SYNOPSIS

        public Value VisitUnaryOperator(UnaryOperator a_unary);
            a_unary    -> the unary operation to visit and evaluate.

    DESCRIPTION

        Evaluates the expression of the unary operation and performs the
        operation. The result of the operation is returned. If the operation is
        not valid (e.g. adding a string and a number), a type error is thrown.

        Done by traversing down the expression and then passing the value off to
        the helper function to actually perform the operation.

        For example, '-1' would return the Value of -1, and 'NOT TRUE' would
        return the Value of FALSE.

    RETURNS

        The result of the unary operation.

    */
    /**/
    @Override
    public Value VisitUnaryOperator(UnaryOperator a_unary) {
        // Traverse down the expression to get the value
        Value value = a_unary.GetExpression().Accept(this);

        // Perform unary operation (+1, -1, NOT TRUE, etc.)
        return EvaluateUnaryOperation(value, a_unary.GetToken());
    }
    /* public Value VisitUnaryOperator(UnaryOperator a_unary); */

    /**/
    /*
    Interpreter.VisitCall()

    NAME

        VisitCall - visits and evaluates a function call, creating its own scope
        in the process.

    SYNOPSIS

        public Value VisitCall(Call a_call);
            a_call    -> the function call to visit and evaluate.

    DESCRIPTION

        Evaluates the callee of the function call and ensures it is a function.
        It then evaluates the arguments of the function call and ensures they
        match the number of parameters the function has (the arity). If they do,
        it executes the function, either a built-in or user-defined function.

        For built-ins, we do not create a local scope, rather we execute the
        Java function. For user-defined functions, we create a new scope and
        put the parameters names into the scope with the arguments as their
        values. We then execute the body of the function.

    RETURNS

        If a built-in, the result of the built-in function. If user-defined, the
        Value of the return statement, or NULL if there is no return statement.

    */
    /**/
    @Override
    public Value VisitCall(Call a_call) {
        // Get the callee and make sure it is a function
        Value callee = a_call.GetCallee().Accept(this);
        EnforceCallable(callee, a_call.GetLineNumber());
        Function function = callee.AsFunction();

        // Short-circuit out if parameters and arguments are not the same size
        EnforceSameArity(function.GetParameterCount(), a_call.GetArguments().size(), a_call.GetLineNumber());

        // Evaluate all the arguments to get their values
        List<Value> arguments = new ArrayList<>();
        for (Node argument : a_call.GetArguments()) { arguments.add(argument.Accept(this)); }

        // For built-in functions, we need to execute their Java code - it is not a body to traverse
        // Help received: IDE suggestion for ternary
        return function.IsBuiltIn()
            ? ExecuteBuiltInFunction(function.GetBuiltInFunction(), arguments, a_call.GetLineNumber())
            : ExecuteUserDefinedFunction(function, arguments);
    }
    /* public Value VisitCall(Call a_call); */

    /**/
    /*
    Interpreter.VisitIdentifier()

    NAME

        VisitIdentifier - visits and evaluates an identifier, returning the
        value it is bound to.

    SYNOPSIS

        public Value VisitIdentifier(Identifier a_identifier);
            a_identifier    -> the identifier to visit and evaluate.

    DESCRIPTION

        Returns the value of the identifier by looking it up in the current
        scope. If the identifier is not found, the symbol table will throw an
        Undefined Identifier error to inform the user that we don't have any
        information on that variable.

    RETURNS

        Returns the Value of the identifier, if it was defined.

    */
    /**/
    @Override
    public Value VisitIdentifier(Identifier a_identifier) {
        return m_currentScope.GetValue(a_identifier.GetVariableName(), a_identifier.GetLineNumber());
    }
    /* public Value VisitIdentifier(Identifier a_identifier); */


    /**/
    /*
    Interpreter.VisitLiteral()

    NAME

        VisitLiteral - visits and returns the value of a literal.

    SYNOPSIS

        public Value VisitLiteral(Literal a_literal);
            a_literal    -> the literal to visit and evaluate.

    DESCRIPTION

        Returns the value of the literal. Literals are the base values of the
        language, like numbers, strings, and booleans. No actual evaluation gets
        done.

    RETURNS

        The Value of the literal, e.g. NULL, TRUE, "HELLO", 1.

    */
    /**/
    @Override
    public Value VisitLiteral(Literal a_literal) {
        // Handles all literals (e.g. 1, 2.3, "Hello", FALSE, etc.)
        return a_literal.GetValue();
    }
    /* public Value VisitLiteral(Literal a_literal); */

    /**/
    /*
    Interpreter.VisitGroup()

    NAME

        VisitGroup - visits and evaluates a group, returning the value of the
        expression inside.

    SYNOPSIS

        public Value VisitGroup(Group a_group);
            a_group    -> the group to visit and evaluate.

    DESCRIPTION

        Evaluates the expression inside the group and returns the result. Groups
        are used to enforce the order of operations in the language, just as
        parentheses do. For example (1 + 2) is a group expression.

    RETURNS

        The Value of the expression inside the group.

    */
    /**/
    @Override
    public Value VisitGroup(Group a_group) {
        // Handles all parentheses (e.g. (1 + 2) * 3)
        return a_group.GetExpression().Accept(this);
    }
    /* public Value VisitGroup(Group a_group); */

    /**/
    /*
    Interpreter.VisitListExpression()

    NAME

        VisitListExpression - visits and evaluates a list expression, returning
        the list Value.

    SYNOPSIS

        public Value VisitListExpression(ListExpression a_listExpression);
            a_listExpression    -> the list expression to visit and evaluate.

    DESCRIPTION

        Evaluates the expressions inside the list expression and returns it as a
        list Value. As we can define lists with expressions inside each element
        e.g. [1 + 2, 3 * 4], we need to evaluate them first before making them a
        literal.

    RETURNS

        The evaluated list Value.

    */
    /**/
    @Override
    public Value VisitListExpression(ListExpression a_listExpression) {
        // Handles all list expressions (e.g. [1, 2, 3], ["Hello", "World"], etc.)
        return EvaluateListExpression(a_listExpression.GetExpressions());
    }
    /* public Value VisitListExpression(ListExpression a_listExpression); */


    /* PRIVATE */

    /** Members **/

    private SymbolTable m_currentScope;         // The current scope of the block we are in


    /** Private Helper Functions **/

    /*
     *      Binary Expressions - Performing operations on two values
     */

    /**/
    /*
    Interpreter.EvaluateBinaryOperator()

    NAME

        EvaluateBinaryOperator - evaluates a binary operation on two values.

    SYNOPSIS

        private Value EvaluateBinaryOperator(Value a_left, Token a_token,
                                             Value a_right);
            a_left      -> the left value of the binary operation.
            a_token     -> the token/operator of the binary operation.
            a_right     -> the right value of the binary operation.

    DESCRIPTION

        Evaluates the binary operation on the left and right values. The
        operation is determined by the token/operator. If the operation is not
        valid (e.g. adding a string and a number), a type error is thrown. It
        is the center of the interpreter, it performs the actual operations. In
        essence, it translates our values to Java values and performs the
        operations on them.

        For numbers the operation is done with BigDecimals as they contain the
        set of integers. They will be converted back to integers if the starting
        values were integers. This avoids if-else chains for the same operation
        on integers and floats. Java has generics, but they aren't as powerful
        as C++ templates as no operator overloading.

        The use of lambdas was intentional to avoid multiple functions that
        would only be used once and duplicate the same 3-4 lines of code every
        time. This way, the java operation done can be determined within the
        switch and use a more generic function to apply it.

        Our switch expression is used to determine the operation to perform, and
        the lambda is used to apply the operation to the left and right values.
        It should make it clear what operation is being done and how it is being
        done. In case of an invalid operator, an IllegalStateException is thrown
        as something is seriously wrong.

    RETURNS

        The result of the binary operation, if the types are correct. For
        example, 1 + 2 would return the Value of 3, 2 ^ 2 would be 4, and
        "Hello" + "World" would be "HelloWorld".

    */
    /**/
    private Value EvaluateBinaryOperator(Value a_left, Token a_token, Value a_right) {
        OperationCode operator = a_token.GetOpcode();
        int lineNumber = a_token.GetLineNumber();

        // Lambdas are used to reduce code duplication and make it clear what operation is being done
        // Help received for lambdas:
        //      https://stackoverflow.com/a/13604748
        //      https://docs.oracle.com/en/java/javase/17/docs/api/java.base/java/util/function/package-summary.html
        //      https://stackoverflow.com/questions/17913409/what-is-a-sam-type-in-java
        //      IDE suggestion for switch expression
        return switch (operator) {
            /* Logical */
            case AND -> ApplyLogical(a_left, a_right, (a, b) -> a && b, lineNumber, operator);
            case OR -> ApplyLogical(a_left, a_right, (a, b) -> a || b, lineNumber, operator);


            /* Equality */
            case EQUALITY -> ApplyEquality(a_left, a_right, Value::Equals, lineNumber, operator);
            case INEQUALITY -> ApplyEquality(a_left, a_right, (a, b) -> !a.Equals(b), lineNumber, operator);


            /* Comparison */
            // We compare to 0 as BigDecimal.compareTo returns -1 if less than, 0 if equal and 1 if greater than
            // Help received: https://stackoverflow.com/a/34677687
            case LESS_THAN -> ApplyComparison(a_left, a_right, (a) -> a < 0, lineNumber, operator);
            case LESS_THAN_EQUAL -> ApplyComparison(a_left, a_right, (a) -> a <= 0, lineNumber, operator);
            case GREATER_THAN -> ApplyComparison(a_left, a_right, (a) -> a > 0, lineNumber, operator);
            case GREATER_THAN_EQUAL -> ApplyComparison(a_left, a_right, (a) -> a >= 0, lineNumber, operator);


            /* Arithmetic  */
            // Addition has special cases (string and list concatenation)
            case ADD -> ApplyAddition(a_left, a_right, lineNumber, operator);
            case SUBTRACT -> ApplyNumericOperation(a_left, a_right, BigDecimal::subtract, lineNumber, operator);
            case MULTIPLY -> ApplyNumericOperation(a_left, a_right, BigDecimal::multiply, lineNumber, operator);

            // Division and modulo cannot have a right value of 0 (e.g. 3 / 0 and 3 % 0) - want our error, not Java's.
            //      Also need to set precision as irrational numbers will result in an arithmetic exception
            // Help received: https://docs.oracle.com/javase/8/docs/api/java/math/MathContext.html
            case DIVIDE -> ApplyDivmod(a_left, a_right, (a, b) -> a.divide(b,Value.PRECISION), lineNumber, operator);
            case MODULO -> ApplyDivmod(a_left, a_right, (a, b) -> a.remainder(b,Value.PRECISION), lineNumber, operator);

            // No standard operator for power in java so using external library to do calculations
            case POWER -> ApplyPower(a_left, a_right, lineNumber, operator);


            // Should never be able to happen, something is seriously wrong
            default -> throw new IllegalStateException("Invalid operator: " + operator.LABEL);
        };
    }
    /* private Value EvaluateBinaryOperator(Value a_left, Token a_token, Value a_right); */

    /**/
    /*
    Interpreter.ApplyLogical()

    NAME

        ApplyLogical - applies a logical operation to two boolean values.

    SYNOPSIS

        private Value ApplyLogical(Value a_left, Value a_right,
                                   BiPredicate<Boolean, Boolean> a_operation,
                                   int a_lineNumber, OperationCode a_operator);
            a_left          -> the left boolean value.
            a_right         -> the right boolean value.
            a_operation     -> the logical operation/function to apply.
            a_lineNumber    -> the line number the operation was found on
            a_operator      -> the operation code of the operation.

    DESCRIPTION

        Applies the logical operation to the left and right boolean values. The
        operation is determined by the lambda passed in. If the values are not
        booleans, a type error is thrown. It is used for the AND and OR
        operations in the language.

        The lambda passed in is used to apply the operation to the two boolean
        values. It is a BiPredicate as it takes two arguments and returns a
        Java boolean.

    RETURNS

        The result of the logical operation, converted back to our Value.
        For example, TRUE AND FALSE would return FALSE, and TRUE OR FALSE would
        return TRUE.

    */
    /**/
    private Value ApplyLogical(Value a_left, Value a_right, BiPredicate<Boolean, Boolean> a_operation,
                               int a_lineNumber, OperationCode a_operator) {

        // Must be booleans - 5 AND 7 doesn't make much sense (unless you are C)
        EnforceSameTypes(DataType.BOOLEAN, a_left, a_right, a_lineNumber, a_operator);

        // Apply the AND/OR operation
        return new Value(a_operation.test(a_left.AsBoolean(), a_right.AsBoolean()));
    }
    /* private Value ApplyLogical(Value a_left, Value a_right,
                              BiPredicate<Boolean, Boolean> a_operation,
                              int a_lineNumber, OperationCode a_operator); */

    /**/
    /*
    Interpreter.ApplyEquality()

    NAME

        ApplyEquality - applies an equality operation to two values.

    SYNOPSIS

        private Value ApplyEquality(Value a_left, Value a_right,
                                BiFunction<Value, Value, Boolean> a_operation,
                                int a_lineNumber, OperationCode a_operator);
            a_left          -> the left value of the equality operation.
            a_right         -> the right value of the equality operation.
            a_operation     -> the equality operation/function to apply.
            a_lineNumber    -> the line number the operation was found on
            a_operator      -> the operation code of the operation.

    DESCRIPTION

        Applies the equality operation to the left and right values. The
        operation is determined by the lambda passed in. If the values are not
        the same type (or both are not numbers), a type error is thrown. It is
        used for the equality an inequality operations in the language.

        The lambda passed in is used to apply the operation to the two values,
        resulting in a Java boolean.

    RETURNS

        A boolean result of the equality operation, converted back to our Value.
        For example, 1 == 1 would return TRUE, and 1 == "Hello" would throw a
        type error.

    */
    /**/
    private Value ApplyEquality(Value a_left, Value a_right, BiFunction<Value, Value, Boolean> a_operation,
                                int a_lineNumber, OperationCode a_operator) {

        // If both are numbers, we can compare them directly
        if (a_left.IsNumber() && a_right.IsNumber()) { return new Value(a_operation.apply(a_left, a_right)); }

        // Can't compare equality of different types if not numbers - 5 == "hello" doesn't make sense
        EnforceSameTypes(a_left.GetDataType(), a_left, a_right, a_lineNumber, a_operator);

        // Perform the equality check
        return new Value(a_operation.apply(a_left, a_right));
    }
    /* private Value ApplyEquality(Value a_left, Value a_right,
                              BiFunction<Value, Value, Boolean> a_operation,
                              int a_lineNumber, OperationCode a_operator); */

    /**/
    /*
    Interpreter.ApplyComparison()

    NAME

        ApplyComparison - applies a comparison operation to two values.

    SYNOPSIS

        private Value ApplyComparison(Value a_left, Value a_right,
                                  IntPredicate a_operation,
                                  int a_lineNumber, OperationCode a_operator);
            a_left          -> the left value of the comparison operation.
            a_right         -> the right value of the comparison operation.
            a_operation     -> the comparison operation/function to apply.
            a_lineNumber    -> the line number the operation was found on
            a_operator      -> the operation code of the operation.

    DESCRIPTION

        Applies the comparison operation to the left and right values. The
        operation is determined by the IntPredicate passed in. If the values are
        not numbers, a type error is thrown. It is used for the comparison
        operations in the language.

        The IntPredicate passed in is used to apply the operation to the two
        values, resulting in a Java boolean. The comparison is done by
        converting the BigDecimals to floats and then comparing them to avoid
        else-if chains for the same operation on integers and floats.

    RETURNS

        A boolean result of the comparison operation, converted back to our
        Value. For example, 1 < 2 would return TRUE, and 1 < "Hello" would throw
        a type error.

    */
    /**/
    private Value ApplyComparison(Value a_left, Value a_right, IntPredicate a_operation,
                                  int a_lineNumber, OperationCode a_operator) {

        // Must be numbers, can compare integers and floats - 5 < 7 and 5.5 < 7. But can't compare strings or lists
        //      - "hello" < "world" doesn't make sense
        EnforceNumberTypes(a_left, a_right, a_lineNumber, a_operator);

        // As stated BigDecimal.compareTo return an int depending on the comparison - see lambda for more info
        // Help received: https://stackoverflow.com/questions/34677644/how-to-use-comparison-operators-like-on-bigdecimal
        int comparison = a_left.AsFloat().compareTo(a_right.AsFloat());
        return new Value(a_operation.test(comparison));
    }
    /* private Value ApplyComparison(Value a_left, Value a_right,
                              IntPredicate a_operation,
                              int a_lineNumber, OperationCode a_operator); */

    /**/
    /*
    Interpreter.ApplyNumericOperation()

    NAME

        ApplyNumericOperation - applies a numerical operation to two values.

    SYNOPSIS

        private Value ApplyNumericOperation(Value a_left, Value a_right,
                    BiFunction<BigDecimal, BigDecimal, BigDecimal> a_operation,
                    int a_lineNumber, OperationCode a_operator);
            a_left          -> the left value of the numerical operation.
            a_right         -> the right value of the numerical operation.
            a_operation     -> the numerical operation/function to apply.
            a_lineNumber    -> the line number the operation was found on.
            a_operator      -> the operation code of the operation.

    DESCRIPTION

        Applies the numerical operation to the left and right values. The
        operation is determined by the BiFunction passed in. If the values are
        not numbers, a type error is thrown. It is used for the numerical
        operations in the language, like subtraction and multiplication.

        The BiFunction passed in is used to apply the operation to the two
        values, resulting in a BigDecimals and will be converted back to
        integers if the starting two values were integers.

    RETURNS

        The result of the numerical operation, converted back to our Value. For
        example, 2 - 1 would return the Value of 1, and 2 * 3 would return 6.

    */
    /**/
    private Value ApplyNumericOperation(Value a_left, Value a_right,
                                        BiFunction<BigDecimal, BigDecimal, BigDecimal> a_operation,
                                        int a_lineNumber, OperationCode a_operator) {

        // As it's a general numerical operation, we need to enforce that both are numbers
        EnforceNumberTypes(a_left, a_right, a_lineNumber, a_operator);

        // Do the arithmetic operation, and convert back to the correct type (int or float) if both are integers
        BigDecimal result = a_operation.apply(a_left.AsFloat(), a_right.AsFloat());
        return FixBinaryResultType(a_left, a_right, result);
    }
    /* private Value ApplyNumericOperation(Value a_left, Value a_right,
                    BiFunction<BigDecimal, BigDecimal, BigDecimal> a_operation,
                    int a_lineNumber, OperationCode a_operator); */

    /**/
    /*
    Interpreter.ApplyAddition()

    NAME

        ApplyAddition - applies an addition operation to two values.

    SYNOPSIS

        private Value ApplyAddition(Value a_left, Value a_right,
                                    int a_lineNumber, OperationCode a_operator);
            a_left          -> the left value of the addition operation.
            a_right         -> the right value of the addition operation.
            a_lineNumber    -> the line number the operation was found on.
            a_operator      -> the operation code of the operation.

    DESCRIPTION

        Addition is a special case of binary operations as it can be used for
        string concatenation, list extension, and normal number arithmetic. It
        is the most complex of the binary operations due to this, and as a
        result gets its own function.

        The left and right values must be numbers for arithmetic, doing implicit
        conversion if adding integers to floats. These values will be converted
        back to an integer if the starting two were so to begin with. If they
        are strings, they are concatenated. If they are lists, they are extended
        If they are not any of these cases (e.g. adding a string and a number),
        a type error is thrown.

    RETURNS

        The result of the addition operation, converted back to our Value. For
        example, 1 + 2 would return the Value of 3, "Hello" + "World" would
        return "HelloWorld", and [1, 2] + [3, 4] would return [1, 2, 3, 4].

    */
    /**/
    private Value ApplyAddition(Value a_left, Value a_right,
                                int a_lineNumber, OperationCode a_operator) {

        // Both are numbers, so normal arithmetic, e.g. 3 + 2 or 1.5 + 7
        if (a_left.IsNumber() && a_right.IsNumber()) {
           return FixBinaryResultType(a_left, a_right, a_left.AsFloat().add(a_right.AsFloat()));
        }

        // Normal string concatenation, e.g. "hello" + "world"
        if (a_left.IsString() && a_right.IsString()) {
            return new Value(a_left.AsString() + a_right.AsString());
        }
        // Lists we extend, e.g. [1, 2, 3] + [4, 5, 6] = [1, 2, 3, 4, 5, 6]
        if (a_left.IsList() && a_right.IsList()) {
            return new Value(AddLists(a_left.AsList(), a_right.AsList()));
        }

        // Catch if we have different types
        EnforceSameTypes(a_left.GetDataType(), a_left, a_right, a_lineNumber, a_operator);

        // Should not be reachable as EnforceSameType() should catch
        assert false : "Could not add values of different types";
        return Value.NULL;
    }
    /* private Value ApplyAddition(Value a_left, Value a_right,
                                int a_lineNumber, OperationCode a_operator); */

    /**/
    /*
    Interpreter.ApplyDivmod()

    NAME

        ApplyDivmod - applies a division or modulo operation to two values.

    SYNOPSIS

        private Value ApplyDivmod(Value a_left, Value a_right,
                  BiFunction<BigDecimal, BigDecimal, BigDecimal> a_operation,
                  int a_lineNumber, OperationCode a_operator);
            a_left          -> the left value of the operation.
            a_right         -> the right value of the operation.
            a_operation     -> the division/modulo operation to apply.
            a_lineNumber    -> the line number the operation was found on.
            a_operator      -> the operator code of the operation.

    DESCRIPTION

        Applies the division or modulo operation to the left and right values.
        The operation is determined by the BiFunction passed in. If the values
        are not numbers, a type error is thrown. If the right value is 0, a
        division by zero error is thrown. It is used for the division and modulo
        operations in the language. Is in its own function due to the special
        case of division by zero.

        The BiFunction passed in is used to apply the operation to the two
        values, resulting in a BigDecimals and will be converted back to
        integers if the starting two values were integers. So 2 / 3 would be 0
        as we have two integers, and 1 / 2.0 would be 0.5 as we cast to a
        float to get the correct result.

    RETURNS

        The result of the division or modulo operation, converted back to our
        Value.

    */
    /**/
    private Value ApplyDivmod(Value a_left, Value a_right, BiFunction<BigDecimal, BigDecimal, BigDecimal> a_operation,
                              int a_lineNumber, OperationCode a_operator) {

        // Division and modulo can only be done on numbers - 5 / "hello" doesn't make sense
        EnforceNumberTypes(a_left, a_right, a_lineNumber, a_operator);

        // Make into floats now to avoid repeated function calls
        BigDecimal left = a_left.AsFloat(); BigDecimal right = a_right.AsFloat();

        // Can't divide or modulo by 0, doesn't make sense
        EnforceDivmodByZero(right, a_lineNumber, a_operator);

        // Perform operation and fix the result type back to integer if needed
        BigDecimal result = a_operation.apply(left, right);
        return FixBinaryResultType(a_left, a_right, result);
    }
    /* private Value ApplyDivmod(Value a_left, Value a_right,
                  BiFunction<BigDecimal, BigDecimal, BigDecimal> a_operation,
                  int a_lineNumber, OperationCode a_operator); */

    /**/
    /*
    Interpreter.ApplyPower()

    NAME

        ApplyPower - applies a power operation to two values.

    SYNOPSIS

        private Value ApplyPower(Value a_left, Value a_right, int a_lineNumber,
                                 OperationCode a_operator);
            a_left          -> the left value of the power operation.
            a_right         -> the right value of the power operation.
            a_lineNumber    -> the line number the operation was found on.
            a_operator      -> the operator code of the operation.

    DESCRIPTION

        Applies the power operation to the left and right values. If the values
        are not numbers, a type error is thrown. If the result of the power
        operation is too large to handle, an overflow error is thrown. It is
        used for the power operation in the language. Is in its own function due
        to the special case of overflow, and the need for an external library.

        The power operation is done using an external library as Java does not
        have a standard power operation. The result is a BigDecimal, which will
        be converted back to an integer if the starting two values were
        integers. So 2 ^ 3 would be 8 as we have two integers, and 2 ^ 3.0 would
        be 8.0 as we cast to a float to get the correct result.

    RETURNS

        The result of the power operation, converted back to our Value.

    */
    /**/
    private Value ApplyPower(Value a_left, Value a_right, int a_lineNumber, OperationCode a_operator) {

        // Power can only be done on numbers - 5 ^ "hello" doesn't make sense
        EnforceNumberTypes(a_left, a_right, a_lineNumber, a_operator);

        // Power can result in overflow, so we need to catch that. Very complicated to fix and above the scope of
        //      this project to implement. Library is used to calculate as no standard one exists in Java.
        // Library: https://github.com/eobermuhlner/big-math
        try {
            BigDecimal result = BigDecimalMath.pow(a_left.AsFloat(), a_right.AsFloat(), Value.PRECISION);
            return FixBinaryResultType(a_left, a_right, result);
        }
        // We've overflowed, show our error instead of Java's
        catch (ArithmeticException e) {
            throw new Error("Overflow, result of power operation is too large to handle",
                            ErrorType.ARITHMETIC_ERROR,
                            a_lineNumber);
        }
    }
    /* private Value ApplyPower(Value a_left, Value a_right, int a_lineNumber,
                                OperationCode a_operator); */

    /**/
    /*
    Interpreter.AddLists()

    NAME

        AddLists - adds two lists together, returning the result.

    SYNOPSIS

            private List<Value> AddLists(List<Value> a_left,
                                         List<Value> a_right);
                a_left      -> the left list to add.
                a_right     -> the right list to add.

    DESCRIPTION

        Adds the two lists together, keeping the order of the elements. It is
        used for the addition operation in the language when adding two lists
        together. It is a helper function to avoid code duplication and make the
        code more readable.

    RETURNS

        A List<Value> object that is the result of adding the two lists.

    */
    /**/
    private List<Value> AddLists(List<Value> a_left, List<Value> a_right) {
        // Help Received: https://stackoverflow.com/questions/189559/how-do-i-join-two-lists-in-java
        List<Value> result = new ArrayList<>();
        // Add left then right, as we want to keep the order
        result.addAll(a_left);
        result.addAll(a_right);
        return result;
    }

    /**/
    /*
    Interpreter.FixBinaryResultType()

    NAME

        FixBinaryResultType - converts the result of a binary operation back to
        an integer if the left and right values were integers.

    SYNOPSIS

        private Value FixBinaryResultType(Value a_left, Value a_right,
                                          BigDecimal a_result);
            a_left      -> the left value of the binary operation.
            a_right     -> the right value of the binary operation.
            a_result    -> the Java value result of the binary operation.

    DESCRIPTION

        Converts the result of the binary operation back to an integer if the
        left and right values were integers. This avoids if-else chains for the
        same operation on integers and floats. It is used for all binary
        operations in the language.

    RETURNS

        If the left and right values are integers, the converted BigDecimal to
        an integer Value. If they are not, the result is returned as is.

    */
    /**/
    private Value FixBinaryResultType(Value a_left, Value a_right, BigDecimal a_result) {
        // If left and right values are integers, then go back to an integer. Best way to avoid long if-else chains to
        //      perform same operation on float or integer while retaining accuracy.
        // Help received: IDE suggestion for ternary
        return a_left.IsInteger() && a_right.IsInteger() ? new Value(a_result.toBigInteger()) : new Value(a_result);
    }
    /* private Value FixBinaryResultType(Value a_left, Value a_right,
                                         BigDecimal a_result); */


    /*
     *      List and String Access - Accessing subscript and index. We are capped at Java's INTEGER_MAX_VALUE for lists
     *          and strings, so will report if index goes beyond that.
     *
     *      To note: I'm aware of code dupe for strings and lists, as well as index and range subscripts. No way to
     *          really avoid it without making the code more complex and harder to read. Lists and strings have
     *          different methods for length and subscripting so use of Java's generics doesn't work without lambdas.
     *          As for index and range, they are different operations once again, substring() versus charAt() and
     *          subList() versus get(). Pains me to have it like this, but as only 2 types are subscriptable, so I'm ok
     *          with it. Add anymore and I would have to refactor it.
     */

    /**/
    /*
    Interpreter.AccessIndexSubscript()

    NAME

        AccessIndexSubscript - accesses a subscript of a list or string using an index.

    SYNOPSIS

        private Value AccessIndexSubscript(Value a_accessee, Value a_index,
                                           int a_lineNumber);
            a_accessee      -> the list or string to access.
            a_index         -> the index to access at.
            a_lineNumber    -> the line number the operation was found on.

    DESCRIPTION

        Accesses the subscript of a list or string using an index. If the
        accessee is not a list or string, a type error is thrown. If the index is
        out of bounds, an index out of bounds error is thrown. It is used for
        the index subscript operation in the language. We are 0 based indexing,
        so 0 is the first element, 1 is the second, etc. The index must also be
        an integer. We are capped at Java's list and string length (the integer
        max) so will report if index goes beyond that.

    RETURNS

        The Value of the element at the index in the list or string. For example
        "Hello":0 would evaluate to "H", and [1, 2, 3]:2 would evaluate to 3.

    */
    /**/
    private Value AccessIndexSubscript(Value a_accessee, Value a_index, int a_lineNumber) {
        // Can only subscript lists and strings - 5[0] doesn't make sense
        EnforceAccessType(a_accessee, a_lineNumber);

        int index = GetSafeIndex(a_index, a_lineNumber);

        if (a_accessee.IsString()) {
            String string = a_accessee.AsString();
            EnforceIndexBounds(index, string.length(), a_lineNumber);
            // Help received: https://stackoverflow.com/a/11230042
            return new Value(String.valueOf(string.charAt(index)));
        }
        else if (a_accessee.IsList()) {
            List<Value> list = a_accessee.AsList();
            EnforceIndexBounds(index, list.size(), a_lineNumber);
            return list.get(index);     // As a literal, not a list
        }

        // Should not be reachable as EnforceAccessType() should catch it, throw real error
        assert false : "Could not access index subscript";
        return Value.NULL;
    }
    /* private Value AccessIndexSubscript(Value a_accessee, Value a_index,
                                          int a_lineNumber); */

    /**/
    /*
    Interpreter.AccessRangedSubscript()

    NAME

        AccessRangedSubscript - accesses a range of a list or string using a
        start and end index.

    SYNOPSIS

        private Value AccessRangedSubscript(Value a_accessee,
                                        Value a_startIndex, Value a_endIndex,
                                        int a_lineNumber);
            a_accessee      -> the list or string to access.
            a_startIndex    -> the start index of the range to access.
            a_endIndex      -> the end index of the range to access.
            a_lineNumber    -> the line number the operation was found on.

    DESCRIPTION

        Accesses the range of a list or string using a start and end index. If
        the accessee is not a list or string, a type error is thrown. If the
        range is out of bounds, with the range ending at 1 - a_endIndex. If
        these conditions are not met an index out of bounds error is thrown. It
        is used for the range subscript operation in the language. The indices
        must also be integers. Once again we are capped at Java's max integer
        for indexing, so will report if index goes beyond that.

    RETURNS

        The Value of the range of elements in the list or string. For example
        "Hello":0:2 would evaluate to "He", and [1, 2, 3]:1:3 would evaluate to
        [2, 3].

    */
    /**/
    private Value AccessRangedSubscript(Value a_accessee, Value a_startIndex, Value a_endIndex, int a_lineNumber) {
        // Can only subscript lists and strings - 5[0] doesn't make sense
        EnforceAccessType(a_accessee, a_lineNumber);

        // Get our start and end indices with overflow protection
        int startIndex = GetSafeIndex(a_startIndex, a_lineNumber);
        int endIndex = GetSafeIndex(a_endIndex, a_lineNumber);

        // Check if the range is out of bounds then range subscript the value
        if (a_accessee.IsString()) {
            String string = a_accessee.AsString();
            EnforceSubscriptBounds(startIndex, endIndex, string.length(), a_lineNumber);
            return new Value(string.substring(startIndex, endIndex));
        }
        else if (a_accessee.IsList()) {
            List<Value> list = a_accessee.AsList();
            EnforceSubscriptBounds(startIndex, endIndex, list.size(), a_lineNumber);
            // Help received: https://stackoverflow.com/a/32227674
            return new Value(list.subList(startIndex, endIndex));   // As a list, not literal
        }

        // Should not be reachable as EnforceAccessType() should catch it
        assert false : "Could not access ranged subscript";
        return Value.NULL;
    }
    /* private Value AccessRangedSubscript(Value a_accessee,
                                        Value a_startIndex, Value a_endIndex,
                                        int a_lineNumber); */

    /**/
    /*
    Interpreter.GetSafeIndex()

    NAME

        GetSafeIndex - gets the index as an integer, ensuring it is within
        Java's integer limit.

    SYNOPSIS

        private int GetSafeIndex(Value a_index, int a_lineNumber);
            a_index         -> the index to get as an integer.
            a_lineNumber    -> the line number the operation was found on.

    DESCRIPTION

        Gets the index as an integer, ensuring it is within Java's integer
        limit. If the index is not an integer, a type error is thrown. We need
        to do this as we don't have overflow, but are limited to how we can
        represent the index because of Java. We could make our own list object,
        but that is an entirely different project in its own right.

    RETURNS

        The index as a Java integer, ensuring it is within Java's integer limit,
        if it can.

    */
    /**/
    private int GetSafeIndex(Value a_index, int a_lineNumber) {
        // Can't access with non-integer type, nor can we access outside Java's integer limit
        EnforceGenericType(DataType.INTEGER, a_index, a_lineNumber);
        EnforceIndexLimit(a_index.AsInteger(), a_lineNumber);
        return a_index.AsInteger().intValue();
    }
    /* private int GetSafeIndex(Value a_index, int a_lineNumber); */


    /*
     *      Unary Expressions - Performing operations on one value
     */

    /**/
    /*
    Interpreter.EvaluateUnaryOperation()

    NAME

        EvaluateUnaryOperation - evaluates a unary operation on a value.

    SYNOPSIS

        private Value EvaluateUnaryOperation(Value a_value, Token a_token);
            a_value     -> the value to perform the operation on.
            a_token     -> the token containing the operation.

    DESCRIPTION

        Evaluates a unary operation on a value. If the value is not the correct
        type for the operation, a type error is thrown. It is used for the unary
        operations in the language, like negation and logical negation.
        Supported operations are ADD, SUBTRACT, and NOT.

    RETURNS

        The result of the unary operation, converted back to our Value. For
        example, -5 would return -5, and NOT TRUE would return FALSE.

    */
    /**/
    private Value EvaluateUnaryOperation(Value a_value, Token a_token) {
        OperationCode operator = a_token.GetOpcode();
        int lineNumber = a_token.GetLineNumber();

        // Help received: IDE suggestion for switch expression
        return switch (operator) {
            // Add (+1) doesn't do much to a value - done for completeness
            case ADD -> a_value;
            case SUBTRACT -> ApplyNumericalNegation(a_value, lineNumber);
            case NOT -> ApplyLogicalNegation(a_value, lineNumber);

            // Should never be able to happen, something is seriously wrong
            default -> throw new IllegalStateException("Invalid operator for unary: " + operator.LABEL);
        };
    }
    /* private Value EvaluateUnaryOperation(Value a_value, Token a_token); */

    /**/
    /*
    Interpreter.ApplyNumericalNegation()

    NAME

        ApplyNumericalNegation - applies a numerical negation to a value.

    SYNOPSIS

        private Value ApplyNumericalNegation(Value a_value, int a_lineNumber);
            a_value         -> the number value to apply the negation to.
            a_lineNumber    -> the line number the operation was found on.

    DESCRIPTION

        Applies a numerical negation to a value. If the value is not a number, a
        type error is thrown. It is used for the negation operation in the
        language. We use BigDecimals to avoid if-else chains for the numbers. If
        our value was an integer to begin with, we convert it back.

    RETURNS

        The result of the numerical negation, converted back to our Value. For
        example, --5 would return 5, and -5.5 would return -5.5.

    */
    /**/
    private Value ApplyNumericalNegation(Value a_value, int a_lineNumber) {
        // Can only negate (meaning making negative in this case) on numbers - -"hello" doesn't make sense
        EnforceNumberType(a_value, a_lineNumber);

        // Negate and fix the result type back to integer if needed
        BigDecimal negatedValue = a_value.AsFloat().negate();
        return FixUnaryResultType(a_value, negatedValue);
    }
    /* private Value ApplyNumericalNegation(Value a_value, int a_lineNumber); */

    /**/
    /*
    Interpreter.ApplyLogicalNegation()

    NAME

        ApplyLogicalNegation - applies a logical negation to a value.

    SYNOPSIS

        private Value ApplyLogicalNegation(Value a_value, int a_lineNumber);
            a_value         -> the boolean value to apply the negation to.
            a_lineNumber    -> the line number the operation was found on.

    DESCRIPTION

        Applies a logical negation to a value. If the value is not a boolean, a
        type error is thrown. It is used for the logical negation operation in
        the language, so !TRUE would return FALSE, and !FALSE would return TRUE.

    RETURNS

        The result of the Java logical negation, converted back to our Value.

    */
    /**/
    private Value ApplyLogicalNegation(Value a_value, int a_lineNumber) {
        // Logical negation (NOT) can only be done on booleans - NOT 5 doesn't make sense (again unless you are C)
        EnforceGenericType(DataType.BOOLEAN, a_value, a_lineNumber);

        return new Value(!a_value.AsBoolean());
    }
    /* private Value ApplyLogicalNegation(Value a_value, int a_lineNumber); */

    /**/
    /*
    Interpreter.FixUnaryResultType()

    NAME

        FixUnaryResultType - converts the result of a unary operation back to
        an integer if the value was an integer.

    SYNOPSIS

        private Value FixUnaryResultType(Value a_value, BigDecimal a_result);
            a_value     -> the value that was operated on.
            a_result    -> the Java value result of the unary operation.

    DESCRIPTION

        Converts the result of the unary operation back to an integer if the
        value was an integer. This avoids if-else chains for the same operation
        on integers and floats. Similar to FixBinaryResultType, but for only 1
        value.

    RETURNS

        If the value was an integer, the converted BigDecimal to an integer
        Value. If it was not, the result is returned as is.

    */
    /**/
    private Value FixUnaryResultType(Value a_value, BigDecimal a_result) {
        // Same as binary result, but for only 1 value where we need to fix the type back to integer if needed
        // Help received: IDE suggestion for ternary
        return a_value.IsInteger() ? new Value(a_result.toBigInteger()) : new Value(a_result);
    }


    /*
     *      List Expressions - Performing operations on lists
     */

    /**/
    /*
    Interpreter.EvaluateListExpression()

    NAME

        EvaluateListExpression - evaluates a list expression.

    SYNOPSIS

        private Value EvaluateListExpression(List<Node> a_unevaluatedList);
            a_unevaluatedList      -> the list of unevaluated nodes to evaluate.

    DESCRIPTION

        Evaluates a list expression. It evaluates each element in the list and
        makes them into values. If an element is a list, it will automatically
        recurse and evaluate itself. For example, [1+2, 3*4] would evaluate to
        [3, 12].

    RETURNS

        The list as our Value object, with each element evaluated and made into
        a literal.

    */
    /**/
    private Value EvaluateListExpression(List<Node> a_unevaluatedList) {
        List<Value> values = new ArrayList<>();

        // Evaluate each element in the list and make them into values. If an element is a list, it will automatically
        //      recurse and evaluate itself.
        for (Node element : a_unevaluatedList) { values.add(element.Accept(this)); }

        return new Value(values);
    }
    /* private Value EvaluateListExpression(List<Node> a_unevaluatedList); */


    /*
     *      Calling Functions - Making sure we can call them and executing them
     */

    /**/
    /*
    Interpreter.ExecuteBuiltInFunction()

    NAME

        EvaluateFunctionCall - evaluates a built-in function call.

    SYNOPSIS

        private Value ExecuteBuiltInFunction(BuiltInFunctions.BuiltIn a_function,
                                             List<Value> a_arguments,
                                             int a_lineNumber);
            a_function      -> the built-in function to execute.
            a_arguments     -> the arguments to pass to the function.
            a_lineNumber    -> the line number the function was called on.

    DESCRIPTION

        Runs the Java code associated with the built-in function (passed in by
        a_function) and returns the result. If there is an error within the
        built-in, it will be caught and rethrown as our error to include the
        line number it occurred on. The arguments are passed to the built-in
        function to execute.

        If the built-in function is not found, an error is thrown.

    RETURNS

        The result of the built-in function, if no error appears.

    */
    /**/
    private Value ExecuteBuiltInFunction(BuiltInFunctions.BuiltIn a_function, List<Value> a_arguments,
                                         int a_lineNumber) {


        // Try to execute built-in and return its value if no error
        try { return a_function.Execute(a_arguments); }

        // There was likely something wrong with how built-in was called, so rethrow what the message was
        catch (BuiltInFunctions.BuiltInFunctionException BuiltInError) {
            throw new Error(BuiltInError.GetMessage(),
                            ErrorType.BUILT_IN_ERROR,
                            a_lineNumber);
        }
    }

    /**/
    /*
    Interpreter.ExecuteUserDefinedFunction()

    NAME

        ExecuteUserDefinedFunction - executes a user-defined function.

    SYNOPSIS

        private Value ExecuteUserDefinedFunction(Function a_function,
                                                 List<Value> a_arguments);
            a_function      -> the user-defined function to execute.
            a_arguments     -> the arguments to pass to the function.

    DESCRIPTION

        Executes a user-defined function. It creates a new scope for the
        function and puts all arguments into it with their respective variable
        names, and executes the function's body. If the function returns a
        value, it is caught and returned.

    RETURNS

        The Value within the ReturnException thrown by the function, if it had
        one. If it didn't, it returns NULL - every function returns something.

    */
    /**/
    private Value ExecuteUserDefinedFunction(Function a_function, List<Value> a_arguments) {
        // Ensure the number of parameters and arguments are the same, if not it's a caller error
        List<Identifier> parameters = a_function.GetParameters();
        assert parameters.size() == a_arguments.size();

        // Create a new scope for the function
        SymbolTable previousScope = m_currentScope;
        m_currentScope = new SymbolTable(m_currentScope);

        // Put all arguments into new scope with their respective variables
        for (int index = 0; index < a_function.GetParameterCount(); index++) {
            m_currentScope.PutIdentifier(parameters.get(index).GetVariableName(), a_arguments.get(index));
        }

        // Functions return or NULL if no return statement, so we set our return to such
        Value returnValue = Value.NULL;

        // Execute the function's body, at any point it returns a value, we catch it and return it
        try { a_function.GetBody().Accept(this); }
        catch (Jump.ReturnException data) { returnValue = data.GetValue(); }

        // Restore the previous scope
        m_currentScope = previousScope;

        return returnValue;
    }
    /* private Value ExecuteUserDefinedFunction(Function a_function,
                                                 List<Value> a_arguments); */

    /*
     *      Type Enforcement - Laying down the law of type safety
     */

    /**/
    /*
    Interpreter.EnforceSameTypes()

    NAME

        EnforceSameTypes - ensures two values are the same type.

    SYNOPSIS

        private void EnforceSameTypes(Value.DataType a_expectedType, Value a_left,
                                      Value a_right, int a_lineNumber,
                                      OperationCode a_operator);
            a_expectedType  -> the expected type of the values.
            a_left          -> the left value to compare.
            a_right         -> the right value to compare.
            a_lineNumber    -> the line number the operation was found on.
            a_operator      -> the operator code of the operation.

    DESCRIPTION

        Ensures two values are the same type. If they are not, a type error is
        thrown. It is used for binary operations where the types must be the
        same, e.g. subtracting two numbers or adding two strings.

    RETURNS

        Nothing, but throws an error if the types are not the expected.

    */
    /**/
    private void EnforceSameTypes(Value.DataType a_expectedType, Value a_left, Value a_right,
                                  int a_lineNumber, OperationCode a_operator) {
        // If both our values are not the expected type, we have a type error
        if (!(a_left.GetDataType() == a_expectedType && a_right.GetDataType() == a_expectedType)) {
            throw new Error("Cannot perform '" + a_operator.LABEL + "' to types '" +
                                a_left.GetDataType() + "' and '" + a_right.GetDataType() + "'",
                           ErrorType.TYPE_ERROR,
                           a_lineNumber);
        }
    }
    /* private void EnforceSameTypes(Value.DataType a_expectedType,
                                Value a_left, Value a_right,
                                int a_lineNumber, OperationCode a_operator); */

    /**/
    /*
    Interpreter.EnforceNumberTypes()

    NAME

        EnforceNumberTypes - ensures two values are numbers.

    SYNOPSIS

        private void EnforceNumberTypes(Value a_left, Value a_right,
                                    int a_lineNumber, OperationCode a_operator);
            a_left          -> the left value to compare.
            a_right         -> the right value to compare.
            a_lineNumber    -> the line number the operation was found on.
            a_operator      -> the operator code of the operation.

    DESCRIPTION

        Ensures two values are numbers. If they are not, a type error is thrown.
        It is used for binary operations where the values must be numbers, e.g.
        dividing two numbers or multiplying two numbers.

    RETURNS

        Nothing, but throws an error if the values are not numbers.

    */
    /**/
    private void EnforceNumberTypes(Value a_left, Value a_right, int a_lineNumber, OperationCode a_operator) {
        // If both not a number, we have a type error
        if (!(a_left.IsNumber() && a_right.IsNumber())) {
            throw new Error("Expected two number types for '" + a_operator.LABEL + "', got '" +
                    a_left.GetDataType() + "' and '" + a_right.GetDataType() + "'",
                    ErrorType.TYPE_ERROR,
                    a_lineNumber);
        }
    }
    /* private void EnforceNumberTypes(Value a_left, Value a_right,
                                int a_lineNumber, OperationCode a_operator); */

    /**/
    /*
    Interpreter.EnforceAccessType()

    NAME

        EnforceAccessType - ensures the value is subscriptable.

    SYNOPSIS

        private void EnforceAccessType(Value a_accessee, int a_lineNumber);
            a_accessee      -> the value to check if it is subscriptable.
            a_lineNumber    -> the line number the accessee was found on.

    DESCRIPTION

        Ensures the value is subscriptable. If it is not a string or list, a
        type error is thrown.

    RETURNS

        Nothing, but throws an error if the value is not subscriptable.

    */
    /**/
    private void EnforceAccessType(Value a_accessee, int a_lineNumber) {
        // If the accessee is not a string or list, we can't access it
        if (!(a_accessee.IsString() || a_accessee.IsList())) {
            throw new Error("Type '" + a_accessee.GetDataType() + "' is not subscriptable",
                            ErrorType.TYPE_ERROR,
                            a_lineNumber);
        }
    }
    /* private void EnforceAccessType(Value a_accessee, int a_lineNumber); */

    /**/
    /*
    Interpreter.EnforceGenericType()

    NAME

        EnforceGenericType - ensures the value is the expected type.

    SYNOPSIS

        private void EnforceGenericType(Value.DataType a_expectedType,
                                        Value a_value, int a_lineNumber);
            a_expectedType  -> the expected type of the value.
            a_value         -> the value to check if it is the expected type.
            a_lineNumber    -> the line number the value was found on.
    */
    /**/
    private void EnforceGenericType(Value.DataType a_expectedType, Value a_value, int a_lineNumber) {
        // If the expected type does not match our values type, we have a type error
        if (a_value.GetDataType() != a_expectedType) {
            throw new Error("Expected '" + a_expectedType + "', got '" + a_value.GetDataType() + "'",
                            ErrorType.TYPE_ERROR,
                            a_lineNumber);
        }
    }
    /* private void EnforceGenericType(Value.DataType a_expectedType,
                                       Value a_value, int a_lineNumber); */

    /**/
    /*
    Interpreter.EnforceNumberType()

    NAME

        EnforceNumberType - ensures the value is a number.

    SYNOPSIS

        private void EnforceNumberType(Value a_value, int a_lineNumber);
            a_value         -> the value to check if it is a number.
            a_lineNumber    -> the line number the value was found on.

    DESCRIPTION

        Ensures the value is a number. If it is not, a type error is thrown.

    RETURNS

        Nothing, but throws an error if the value is not a number.

    */
    /**/
    private void EnforceNumberType(Value a_value, int a_lineNumber) {
        // If the value is not a number, we have a type error
        if (!a_value.IsNumber()) {
            throw new Error("Expected number, got '" + a_value.GetDataType() + "'",
                            ErrorType.TYPE_ERROR,
                            a_lineNumber);
        }
    }
    /* private void EnforceNumberType(Value a_value, int a_lineNumber); */

    /**/
    /*
    Interpreter.EnforceLoopTypes()

    NAME

        EnforceLoopTypes - ensures the values in a for loop are integers.

    SYNOPSIS

        private void EnforceLoopTypes(Value a_assignment, Value a_endValue,
                                      Value a_increment, int a_lineNumber);
            a_assignment   -> the assignment value in the for loop.
            a_endValue     -> the end value in the for loop.
            a_increment    -> the increment value in the for loop.
            a_lineNumber   -> the line number the for loop was found on.

    DESCRIPTION

        Ensures the values in a for loop are integers. If they are not, a type
        error is thrown. It is used for the for loop in the language. Does it
        in a way that will show all errors at once to the user, making it easier
        to debug.

    RETURNS

        Nothing, but throws an error if the values are not integers.

    */
    /**/
    private void EnforceForLoopTypes(Value a_assignment, Value a_endValue, Value a_increment, int a_lineNumber) {
        List<String> errors = new ArrayList<>();

        // If any of the values are not integers, we have a type error
        if (!a_assignment.IsInteger()) { errors.add("assignment (got '" + a_assignment.GetDataType() + "')"); }
        if (!a_endValue.IsInteger()) { errors.add("end value (got '" + a_endValue.GetDataType() + "')"); }
        if (!a_increment.IsInteger()) { errors.add("increment (got '" + a_increment.GetDataType() + "')"); }

        // If there are no errors, we are good to go
        if (errors.isEmpty()) { return; }

        // Help received: https://www.geeksforgeeks.org/java-string-join-examples/
        String message = "Expected '" + DataType.INTEGER + "' for " + String.join(", ", errors);

        // Print out the errors with commas and an 'and' at the end if there are more than 1 to help user identify
        //      what they did wrong. Makes it more specific and easier to understand for user.
        // Help received: https://www.w3schools.com/java/ref_string_lastindexof.asp
        int lastComma = message.lastIndexOf(", ");
        if (lastComma != -1) {
            message = message.substring(0, lastComma) + " and" + message.substring(lastComma + 1);
        }

        throw new Error(message,
                        ErrorType.TYPE_ERROR,
                        a_lineNumber);
    }
    /* private void EnforceForLoopTypes(Value a_assignment, Value a_endValue,
                                      Value a_increment, int a_lineNumber); */

    
    /*
     *      Function Enforcement - Making sure functions are called correctly
     */

    /**/
    /*
    Interpreter.EnforceCallable()

    NAME

        EnforceCallable - ensures the value is a function.

    SYNOPSIS

        private void EnforceCallable(Value a_function, int a_lineNumber);
            a_function      -> the value to check if it is a function.
            a_lineNumber    -> the line number the function was found on.

    DESCRIPTION

        Ensures the value is a function. If it is not, a type error is thrown.

    RETURNS

        Nothing, but throws an error if the value is not a function.

    */
    /**/
    private void EnforceCallable(Value a_function, int a_lineNumber) {
        // If the value is not a function, we can't call it
        if (!a_function.IsFunction()) {
            throw new Error("Cannot call non-function type",
                    ErrorType.TYPE_ERROR,
                    a_lineNumber);
        }
    }
    /* private void EnforceCallable(Value a_function, int a_lineNumber); */

    /**/
    /*
    Interpreter.EnforceSameArity()

    NAME

        EnforceSameArity - ensures the number of parameters and arguments are
        the same for a call and function.

    SYNOPSIS

        private void EnforceSameArity(int a_functionParameters,
                                      int a_callArguments,
                                      int a_lineNumber);
            a_functionParameters -> the number of parameters in the function.
            a_callArguments      -> the number of arguments in the call.
            a_lineNumber         -> the line number the call was found on.

    DESCRIPTION

        Ensures the number of parameters and arguments are the same for a call
        and function. If they are not, a runtime is thrown. It is used for
        function calls where the number of parameters and arguments must be the
        same, e.g. calling a function with 3 arguments when it only takes 2.

    RETURNS

        Nothing, but throws an error if the number of parameters and arguments
        are not the same.

    */
    /**/
    private void EnforceSameArity(int a_functionParameters, int a_callArguments, int a_lineNumber) {
        // If the expected and actual number of arguments are not the same, we have a type error
        if (a_functionParameters != a_callArguments) {
            throw new Error("Expected " + a_functionParameters + " argument(s), got " + a_callArguments,
                    ErrorType.RUNTIME_ERROR,
                    a_lineNumber);
        }
    }
    /* private void EnforceSameArity(int a_functionParameters,
                                     int a_callArguments,
                                     int a_lineNumber); */

    
    /*
     *      Jump Enforcement - Making jump statements are in the correct place
     */

    /**/
    /*
    Interpreter.ErrorOnJump()

    NAME

        ErrorOnJump - throws an error for a jump statement outside of a loop.

    SYNOPSIS

        private void ErrorOnJump(String a_statement, int a_lineNumber);
            a_statement     -> the jump statement that was found.
            a_lineNumber    -> the line number the jump statement was found on.

    DESCRIPTION

        Throws an error for a jump statement outside of a loop. Very specific
        case where syntax is correct, as something like BREAK can be within
        a nested function definition inside a loop, but can't actually be
        evaluted due to the nest.

    RETURNS

        Nothing, but throws an error for a jump statement outside of a loop.

    */
    /**/
    private void ErrorOnJump(String a_statement, int a_lineNumber) {
        throw new Error(a_statement + " statement outside of loop",
                ErrorType.RUNTIME_ERROR,
                a_lineNumber);
    }


    /*
     *      Index and Subscript Enforcement - Making sure we don't go out of bounds
     */

    /**/
    /*
    Interpreter.EnforceIndexBounds()

    NAME

        EnforceIndexBounds - ensures the index is within the bounds of the list
        or string.

    SYNOPSIS

        private void EnforceIndexBounds(int a_index, int a_size, int a_lineNumber);
            a_index         -> the index to check if it is within bounds.
            a_size          -> the size of the list or string.
            a_lineNumber    -> the line number the index was found on.

    DESCRIPTION

        Ensures the index is within the bounds of the list or string. If it is
        not, an index out of bounds error is thrown. It is used for subscripting
        a list or string with an index.

    RETURNS

        Nothing, but throws an error if the index is out of bounds.

    */
    /**/
    private void EnforceIndexBounds(int a_index, int a_size, int a_lineNumber) {
        // If the index is out of bounds not in range, can't subscript it
        if (a_index < 0 || a_index >= a_size) {
            throw new Error("Index " + a_index + " is not in range for length " + a_size,
                            ErrorType.OUT_OF_BOUNDS_ERROR,
                            a_lineNumber);
        }
    }
    /* private void EnforceIndexBounds(int a_index, int a_size,
                                       int a_lineNumber); */

    /**/
    /*
    Interpreter.EnforceSubscriptBounds()

    NAME

        EnforceSubscriptBounds - ensures the range is within the bounds of the
        list or string.

    SYNOPSIS

        private void EnforceSubscriptBounds(int a_startIndex, int a_endIndex,
                                            int a_size, int a_lineNumber);
            a_startIndex    -> the start index of the range to check.
            a_endIndex      -> the end index of the range to check.
            a_size          -> the size of the list or string.
            a_lineNumber    -> the line number the range was found on.

    DESCRIPTION

        Ensures the range is within the bounds of the list or string. If it is
        not, an index out of bounds error is thrown. It is used for subscripting
        a list or string with a range.

    RETURNS

        Nothing, but throws an error if the range is out of bounds.

    */
    /**/
    private void EnforceSubscriptBounds(int a_startIndex, int a_endIndex, int a_size, int a_lineNumber) {
        // If not in range and end is not less than start, can't subscript it
        if (a_startIndex < 0 || (a_endIndex > a_size || a_endIndex < a_startIndex)) {
            throw new Error("Range " + a_startIndex + " to " + a_endIndex + " is not in range for length " +
                                a_size,
                            ErrorType.OUT_OF_BOUNDS_ERROR,
                            a_lineNumber);
        }
    }
    /* private void EnforceSubscriptBounds(int a_startIndex, int a_endIndex,
                                           int a_size, int a_lineNumber); */

    /**/
    /*
    Interpreter.EnforceIndexLimit()

    NAME

        EnforceIndexLimit - ensures the index is within Java's integer limit.

    SYNOPSIS

        private void EnforceIndexLimit(BigInteger a_index, int a_lineNumber);
            a_index         -> the index to check if it is within Java's integer
               limit.
            a_lineNumber    -> the line number the index was found on.

    DESCRIPTION

        Ensures the index is within Java's integer limit. If it is not, an index
        out of bounds error is thrown. It is used for subscripting a list or
        string with an index.

    RETURNS

        Nothing, but throws an error if the index is out of bounds.

    */
    /**/
    private void EnforceIndexLimit(BigInteger a_index, int a_lineNumber) {
        // If the index is too large to handle, can't subscript it
        if (a_index.compareTo(BigInteger.valueOf(Integer.MAX_VALUE)) > 0) {
            throw new Error("Index " + a_index + " is too large to handle",
                            ErrorType.OUT_OF_BOUNDS_ERROR,
                            a_lineNumber);
        }
    }
    /* private void EnforceIndexLimit(BigInteger a_index, int a_lineNumber); */
    
    
    /*
     *      Arithmetic Errors - Handling bad arithmetic operations
     */

    /**/
    /*
    Interpreter.EnforceDivmodByZero()

    NAME

        EnforceDivmodByZero - ensures the denominator is not 0 for division or
        modulo.

    SYNOPSIS

        private void EnforceDivmodByZero(BigDecimal a_denominator,
                                         int a_lineNumber,
                                         OperationCode a_operator);
            a_denominator   -> the denominator to check if it is 0.
            a_lineNumber    -> the line number the operation was found on.
            a_operator      -> the operator code of the operation.

    DESCRIPTION

        Ensures the denominator is not 0 for division or modulo. If it is, an
        arithmetic error is thrown. It is used for division and modulo
        operations in the language. What does it mean to divide by 0?

    RETURNS

        Nothing, but throws an error if the denominator is 0.

    */
    /**/
    private void EnforceDivmodByZero(BigDecimal a_denominator,  int a_lineNumber, OperationCode a_operator) {
        // If the denominator is 0, we can't divide or modulo by it
        if (a_denominator.compareTo(BigDecimal.ZERO) == 0) {
            throw new Error("Cannot '" + a_operator.LABEL + "' by 0",
                            ErrorType.ARITHMETIC_ERROR,
                            a_lineNumber);
        }
    }
    /* private void EnforceDivmodByZero(BigDecimal a_denominator,
                                       int a_lineNumber,
                                       OperationCode a_operator); */

}